import { NextRequest, NextResponse } from 'next/server'
import { withX402 } from 'x402-next'

const handler = async (_req: NextRequest) => {
  return NextResponse.json({
    product: 'RulesForge Pro Pack',
    version: '1.0.0',
    purchasedAt: new Date().toISOString(),
    files: [
      { name: '.cursorrules-nextjs16', framework: 'Next.js 16', description: 'App Router + React 19 + TypeScript strict' },
      { name: 'CLAUDE.md-nextjs', framework: 'Next.js', description: 'Full Claude Code config for Next.js projects' },
      { name: '.cursorrules-python', framework: 'Python', description: 'FastAPI + Pydantic + pytest' },
      { name: '.cursorrules-go', framework: 'Go', description: 'Standard library first, error handling, testing' },
      { name: '.cursorrules-rust', framework: 'Rust', description: 'Clippy-clean, ownership patterns, error types' },
      { name: '.cursorrules-react19', framework: 'React 19', description: 'Hooks-first, Server Components, Suspense' },
      { name: '.cursorrules-vue3', framework: 'Vue 3', description: 'Composition API, TypeScript, Pinia' },
      { name: '.cursorrules-svelte5', framework: 'Svelte 5', description: 'Runes, TypeScript, SvelteKit' },
      { name: '.cursorrules-django', framework: 'Django', description: 'DRF + typed views + pytest-django' },
      { name: '.cursorrules-fastapi', framework: 'FastAPI', description: 'Async, Pydantic v2, dependency injection' },
      { name: '.cursorrules-express', framework: 'Express', description: 'TypeScript, Zod validation, error middleware' },
      { name: '.cursorrules-nestjs', framework: 'NestJS', description: 'Decorators, modules, guards, pipes' },
      { name: '.cursorrules-remix', framework: 'Remix', description: 'Loaders, actions, nested routes' },
      { name: '.cursorrules-astro', framework: 'Astro', description: 'Islands, content collections, SSG' },
      { name: '.cursorrules-flutter', framework: 'Flutter', description: 'Riverpod, freezed, clean architecture' },
      { name: '.cursorrules-swift', framework: 'Swift', description: 'SwiftUI, MVVM, Combine, async/await' },
      { name: '.cursorrules-kotlin', framework: 'Kotlin', description: 'Coroutines, Jetpack Compose, MVVM' },
      { name: '.cursorrules-terraform', framework: 'Terraform', description: 'Module structure, state management, tagging' },
      { name: '.cursorrules-docker', framework: 'Docker', description: 'Multi-stage builds, security, compose' },
      { name: '.cursorrules-kubernetes', framework: 'Kubernetes', description: 'Helm charts, resource limits, RBAC' },
      { name: 'CLAUDE.md-react', framework: 'React', description: 'Claude Code config for React SPAs' },
      { name: 'CLAUDE.md-python', framework: 'Python', description: 'Claude Code config for Python projects' },
      { name: 'CLAUDE.md-go', framework: 'Go', description: 'Claude Code config for Go services' },
      { name: 'CLAUDE.md-rust', framework: 'Rust', description: 'Claude Code config for Rust projects' },
      { name: 'CLAUDE.md-vue', framework: 'Vue', description: 'Claude Code config for Vue 3 projects' },
      { name: 'CLAUDE.md-svelte', framework: 'Svelte', description: 'Claude Code config for SvelteKit' },
      { name: 'CLAUDE.md-django', framework: 'Django', description: 'Claude Code config for Django projects' },
      { name: 'CLAUDE.md-fastapi', framework: 'FastAPI', description: 'Claude Code config for FastAPI services' },
      { name: 'CLAUDE.md-express', framework: 'Express', description: 'Claude Code config for Express APIs' },
      { name: 'CLAUDE.md-monorepo', framework: 'Monorepo', description: 'Turborepo/Nx config for Claude Code' },
      { name: '.cursorrules-tailwind', framework: 'Tailwind CSS', description: 'Design system, custom theme, component patterns' },
      { name: '.cursorrules-prisma', framework: 'Prisma', description: 'Schema design, migrations, seed data' },
      { name: '.cursorrules-drizzle', framework: 'Drizzle', description: 'Schema, migrations, query patterns' },
      { name: '.cursorrules-trpc', framework: 'tRPC', description: 'Router structure, middleware, error handling' },
      { name: '.cursorrules-graphql', framework: 'GraphQL', description: 'Schema-first, resolvers, DataLoader' },
      { name: '.cursorrules-playwright', framework: 'Playwright', description: 'Page objects, fixtures, CI config' },
      { name: '.cursorrules-vitest', framework: 'Vitest', description: 'Config, mocking patterns, coverage' },
      { name: '.windsurf-nextjs', framework: 'Next.js (Windsurf)', description: 'Windsurf-specific rules for Next.js' },
      { name: '.windsurf-react', framework: 'React (Windsurf)', description: 'Windsurf-specific rules for React' },
      { name: '.windsurf-python', framework: 'Python (Windsurf)', description: 'Windsurf-specific rules for Python' },
      { name: '.github-copilot-nextjs', framework: 'Next.js (Copilot)', description: 'GitHub Copilot instructions for Next.js' },
      { name: '.github-copilot-python', framework: 'Python (Copilot)', description: 'GitHub Copilot instructions for Python' },
      { name: '.cursorrules-typescript', framework: 'TypeScript', description: 'Strict mode, no-any, discriminated unions' },
      { name: '.cursorrules-elixir', framework: 'Elixir', description: 'Phoenix, Ecto, GenServer patterns' },
      { name: '.cursorrules-ruby', framework: 'Ruby', description: 'Rails 7, Hotwire, RSpec' },
      { name: '.cursorrules-csharp', framework: 'C#', description: '.NET 8, minimal APIs, EF Core' },
      { name: '.cursorrules-java', framework: 'Java', description: 'Spring Boot 3, records, virtual threads' },
      { name: '.cursorrules-php', framework: 'PHP', description: 'Laravel 11, Pest, strict types' },
      { name: 'RULES-GUIDE.md', framework: 'Meta', description: 'How to write and customize your own rules' },
      { name: 'CHANGELOG.md', framework: 'Meta', description: 'Monthly updates and new additions' },
    ],
    totalFiles: 50,
    license: { type: 'commercial', usage: 'Unlimited commercial use. No attribution required.' },
    downloadUrl: '/api/pro-pack/download',
  })
}

export const GET = withX402(handler, '0xCc97e4579eeE0281947F15B027f8Cad022933d7e', {
  price: '$29',
  network: 'base',
  config: { description: 'RulesForge Pro Pack — 50 AI Coding Rule Files' },
})
