export const frameworkOptions = [
  'Next.js',
  'React',
  'Python',
  'Go',
  'Rust',
  'TypeScript',
  'Vue',
  'Svelte',
  'Django',
  'FastAPI',
  'Express',
] as const

export type Framework = (typeof frameworkOptions)[number]

export const styleOptions = [
  'Strict TypeScript',
  'TDD',
  'Minimal comments',
  'Functional style',
  'Performance-first',
] as const

export type StyleOption = (typeof styleOptions)[number]

export const teamSizeOptions = ['Solo', 'Small team', 'Enterprise'] as const
export type TeamSize = (typeof teamSizeOptions)[number]

const rulesTemplates: Record<string, string> = {
  'Next.js': `# CLAUDE.md — Next.js Production Rules
# Generated by RulesForge (rulesforge.com)

## Project Overview
- Framework: Next.js 16 (App Router)
- Language: TypeScript (strict mode)
- Styling: Tailwind CSS v4
- State: React 19 Server Components by default

## Architecture Rules

### File Structure
- Use App Router exclusively — no pages/ directory
- Colocate components with their routes in app/
- Shared components go in components/
- Server Components by default; add 'use client' only when needed

### TypeScript
- strict: true in tsconfig.json — no exceptions
- No \`any\` types — use \`unknown\` and narrow
- Prefer \`interface\` for object shapes, \`type\` for unions/intersections
- All function parameters and return types must be explicitly typed

### Components
- Server Components by default
- Client Components only for: interactivity, browser APIs, state, effects
- Never import server-only code in Client Components
- Use React.Suspense for async Server Components

### Data Fetching
- Use Server Components + async/await for data fetching
- No useEffect for data fetching — use Server Components
- Cache with \`unstable_cache\` or React \`cache()\` for deduplication
- Always handle loading states with loading.tsx

### Performance
- Use next/image for all images — no raw <img> tags
- Use next/font for font loading
- Implement proper metadata with generateMetadata
- Use dynamic imports for heavy client components
- Keep Client Component bundles small

### Error Handling
- Every route segment should have an error.tsx boundary
- Use notFound() for 404 cases, not redirects
- Log errors server-side, show user-friendly messages client-side

### Testing
- Use Vitest for unit tests
- Use Playwright for E2E tests
- Test Server Components with async rendering
- Minimum 80% coverage on business logic

### Security
- Validate all inputs with Zod
- Use server actions for mutations — never expose API keys client-side
- Implement rate limiting on API routes
- Sanitize user-generated content before rendering

### Git Conventions
- Conventional commits: feat|fix|docs|refactor|test|chore
- One feature per branch
- PR descriptions must include: what, why, testing steps
`,

  React: `# CLAUDE.md — React Production Rules
# Generated by RulesForge (rulesforge.com)

## Project Overview
- Framework: React 19
- Language: TypeScript (strict mode)
- Build: Vite
- State: Zustand or React Context

## Architecture Rules

### Component Design
- Functional components only — no class components
- Props interface defined above component, exported separately
- Use composition over prop drilling
- Maximum 150 lines per component file

### TypeScript
- strict: true — no exceptions
- No \`any\` — use \`unknown\` and type guards
- Generic components where reuse is needed
- Discriminated unions for complex state

### State Management
- Local state with useState for UI-only state
- Zustand for shared/global state
- React Query/TanStack Query for server state
- No Redux unless absolutely necessary

### Performance
- React.memo only when profiler shows re-render issues
- useMemo/useCallback for expensive computations and stable references
- Virtualize long lists (TanStack Virtual)
- Code-split routes with React.lazy + Suspense

### Testing
- React Testing Library for component tests
- Test behavior, not implementation
- MSW for API mocking
- 80%+ coverage on business logic
`,

  Python: `# CLAUDE.md — Python Production Rules
# Generated by RulesForge (rulesforge.com)

## Project Overview
- Language: Python 3.12+
- Type Checking: mypy (strict mode)
- Formatter: Ruff
- Testing: pytest

## Architecture Rules

### Code Style
- Type hints on all function signatures — no exceptions
- Dataclasses or Pydantic models for structured data
- No mutable default arguments
- Use pathlib.Path instead of os.path

### Error Handling
- Custom exception hierarchy per domain
- Never catch bare Exception — be specific
- Use contextlib for resource management
- Log exceptions with structured logging (structlog)

### Testing
- pytest with fixtures, no unittest.TestCase
- Parametrize for multiple input scenarios
- Use factories (factory_boy) over fixtures for test data
- 90%+ coverage on business logic

### Dependencies
- Pin exact versions in requirements.txt / pyproject.toml
- Use virtual environments always
- Minimal dependency policy — stdlib first
`,

  Go: `# CLAUDE.md — Go Production Rules
# Generated by RulesForge (rulesforge.com)

## Project Overview
- Language: Go 1.22+
- Linter: golangci-lint
- Testing: stdlib testing + testify

## Architecture Rules

### Code Style
- Standard library first — avoid unnecessary dependencies
- Accept interfaces, return structs
- Error handling: always check errors, wrap with fmt.Errorf + %w
- No init() functions unless absolutely necessary

### Naming
- Short variable names in small scopes (i, v, ctx)
- Descriptive names for exported functions and types
- Package names: short, lowercase, no underscores
- Interface names: -er suffix for single-method (Reader, Writer)

### Concurrency
- Don't start goroutines without knowing how they stop
- Use context.Context for cancellation
- Prefer channels for communication, mutexes for state
- Use errgroup for parallel work with error handling

### Testing
- Table-driven tests as default pattern
- Test the public API, not internals
- Use testcontainers for integration tests
- Benchmark critical paths
`,

  Rust: `# CLAUDE.md — Rust Production Rules
# Generated by RulesForge (rulesforge.com)

## Project Overview
- Language: Rust (latest stable)
- Linting: clippy (pedantic)
- Formatter: rustfmt
- Testing: built-in + proptest

## Architecture Rules

### Code Style
- clippy::pedantic clean — no allowed warnings in CI
- Prefer &str over String in function parameters
- Use thiserror for library errors, anyhow for applications
- Derive traits in consistent order: Debug, Clone, PartialEq, Eq, Hash

### Ownership
- Prefer borrowing over cloning
- Use Cow<str> for flexible ownership
- Arc only when shared across threads
- Box for recursive types and trait objects

### Error Handling
- Custom error types per module with thiserror
- Never unwrap() in production code — use expect() with context or ?
- Result<T, E> for all fallible operations
- Map errors at boundaries with .map_err()

### Testing
- Unit tests in same file (mod tests)
- Integration tests in tests/ directory
- Property-based testing with proptest for parsers/serializers
- Benchmark with criterion
`,
}

export function generateRules(
  framework: Framework,
  styles: StyleOption[],
  teamSize: TeamSize
): string {
  let base = rulesTemplates[framework] || rulesTemplates['Next.js']

  if (styles.includes('TDD')) {
    base += `\n## TDD Workflow
- Write test FIRST, see it fail
- Write minimal code to pass
- Refactor with green tests
- No code without a corresponding test
`
  }

  if (styles.includes('Performance-first')) {
    base += `\n## Performance Budget
- First Contentful Paint: < 1.5s
- Time to Interactive: < 3s
- Bundle size per route: < 100KB gzipped
- Lighthouse score: > 90 on all metrics
`
  }

  if (teamSize === 'Enterprise') {
    base += `\n## Enterprise Standards
- All PRs require 2 approvals
- Mandatory CI/CD pipeline pass before merge
- Documentation required for all public APIs
- ADR (Architecture Decision Records) for significant changes
- Security review for auth/payment changes
`
  } else if (teamSize === 'Small team') {
    base += `\n## Team Conventions
- PRs require 1 approval
- Automated CI checks must pass
- Update README for new features
- Weekly dependency updates
`
  }

  return base
}

export const proPackFiles = [
  { name: '.cursorrules-nextjs16', framework: 'Next.js 16', description: 'App Router + React 19 + TypeScript strict' },
  { name: 'CLAUDE.md-nextjs', framework: 'Next.js', description: 'Full Claude Code config for Next.js projects' },
  { name: '.cursorrules-react19', framework: 'React 19', description: 'Hooks-first, Server Components, Suspense' },
  { name: 'CLAUDE.md-react', framework: 'React', description: 'Claude Code config for React SPAs' },
  { name: '.cursorrules-python', framework: 'Python', description: 'FastAPI + Pydantic + pytest' },
  { name: 'CLAUDE.md-python', framework: 'Python', description: 'Claude Code config for Python projects' },
  { name: '.cursorrules-go', framework: 'Go', description: 'Standard library first, error handling, testing' },
  { name: 'CLAUDE.md-go', framework: 'Go', description: 'Claude Code config for Go services' },
  { name: '.cursorrules-rust', framework: 'Rust', description: 'Clippy-clean, ownership patterns, error types' },
  { name: 'CLAUDE.md-rust', framework: 'Rust', description: 'Claude Code config for Rust projects' },
  { name: '.cursorrules-typescript', framework: 'TypeScript', description: 'Strict mode, no-any, discriminated unions' },
  { name: '.cursorrules-vue3', framework: 'Vue 3', description: 'Composition API, TypeScript, Pinia' },
  { name: 'CLAUDE.md-vue', framework: 'Vue', description: 'Claude Code config for Vue 3 projects' },
  { name: '.cursorrules-svelte5', framework: 'Svelte 5', description: 'Runes, TypeScript, SvelteKit' },
  { name: 'CLAUDE.md-svelte', framework: 'Svelte', description: 'Claude Code config for SvelteKit' },
  { name: '.cursorrules-django', framework: 'Django', description: 'DRF + typed views + pytest-django' },
  { name: 'CLAUDE.md-django', framework: 'Django', description: 'Claude Code config for Django projects' },
  { name: '.cursorrules-fastapi', framework: 'FastAPI', description: 'Async, Pydantic v2, dependency injection' },
  { name: 'CLAUDE.md-fastapi', framework: 'FastAPI', description: 'Claude Code config for FastAPI services' },
  { name: '.cursorrules-express', framework: 'Express', description: 'TypeScript, Zod validation, error middleware' },
  { name: 'CLAUDE.md-express', framework: 'Express', description: 'Claude Code config for Express APIs' },
  { name: '.cursorrules-nestjs', framework: 'NestJS', description: 'Decorators, modules, guards, pipes' },
  { name: '.cursorrules-remix', framework: 'Remix', description: 'Loaders, actions, nested routes' },
  { name: '.cursorrules-astro', framework: 'Astro', description: 'Islands, content collections, SSG' },
  { name: '.cursorrules-flutter', framework: 'Flutter', description: 'Riverpod, freezed, clean architecture' },
  { name: '.cursorrules-swift', framework: 'Swift', description: 'SwiftUI, MVVM, Combine, async/await' },
  { name: '.cursorrules-kotlin', framework: 'Kotlin', description: 'Coroutines, Jetpack Compose, MVVM' },
  { name: '.cursorrules-elixir', framework: 'Elixir', description: 'Phoenix, Ecto, GenServer patterns' },
  { name: '.cursorrules-ruby', framework: 'Ruby', description: 'Rails 7, Hotwire, RSpec' },
  { name: '.cursorrules-csharp', framework: 'C#', description: '.NET 8, minimal APIs, EF Core' },
  { name: '.cursorrules-java', framework: 'Java', description: 'Spring Boot 3, records, virtual threads' },
  { name: '.cursorrules-php', framework: 'PHP', description: 'Laravel 11, Pest, strict types' },
  { name: '.cursorrules-terraform', framework: 'Terraform', description: 'Module structure, state management, tagging' },
  { name: '.cursorrules-docker', framework: 'Docker', description: 'Multi-stage builds, security, compose' },
  { name: '.cursorrules-kubernetes', framework: 'Kubernetes', description: 'Helm charts, resource limits, RBAC' },
  { name: 'CLAUDE.md-monorepo', framework: 'Monorepo', description: 'Turborepo/Nx config for Claude Code' },
  { name: '.cursorrules-tailwind', framework: 'Tailwind CSS', description: 'Design system, custom theme, component patterns' },
  { name: '.cursorrules-prisma', framework: 'Prisma', description: 'Schema design, migrations, seed data' },
  { name: '.cursorrules-drizzle', framework: 'Drizzle', description: 'Schema, migrations, query patterns' },
  { name: '.cursorrules-trpc', framework: 'tRPC', description: 'Router structure, middleware, error handling' },
  { name: '.cursorrules-graphql', framework: 'GraphQL', description: 'Schema-first, resolvers, DataLoader' },
  { name: '.cursorrules-playwright', framework: 'Playwright', description: 'Page objects, fixtures, CI config' },
  { name: '.cursorrules-vitest', framework: 'Vitest', description: 'Config, mocking patterns, coverage' },
  { name: '.windsurf-nextjs', framework: 'Next.js (Windsurf)', description: 'Windsurf-specific rules for Next.js' },
  { name: '.windsurf-react', framework: 'React (Windsurf)', description: 'Windsurf-specific rules for React' },
  { name: '.windsurf-python', framework: 'Python (Windsurf)', description: 'Windsurf-specific rules for Python' },
  { name: '.github-copilot-nextjs', framework: 'Next.js (Copilot)', description: 'GitHub Copilot instructions for Next.js' },
  { name: '.github-copilot-python', framework: 'Python (Copilot)', description: 'GitHub Copilot instructions for Python' },
  { name: 'RULES-GUIDE.md', framework: 'Meta', description: 'How to write and customize your own rules' },
  { name: 'CHANGELOG.md', framework: 'Meta', description: 'Monthly updates and new additions' },
]
